name: Publish
on:
  push:
    branches:
      - main
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Deps
        run: |
          npm install -g pnpm
          node common/scripts/install-run-rush.js check
          node common/scripts/install-run-rush.js install
      # - name: Build Packages
      # - name: Unit Test
      # - name: Release Packages
